Repository KennethanCeyer/pg-calendar, pull requests merged in 2019-07, with the labels that each got.

#104 Adding Catalan Language
  src/js/configures/i18n.js
Labels: flow: picked

#109 hotfix/travis-yml
  .travis.yml
Labels: issue: bug

#100 Add support for Arabic language
  src/js/configures/i18n.js
Labels: flow: picked

#110 feature/add-contributor-language-info
  Gruntfile.js
  README.md
  dist/js/pignose.calendar.full.js
  dist/js/pignose.calendar.full.min.js
  dist/js/pignose.calendar.js
  dist/js/pignose.calendar.min.js
  index.html
  package-lock.json
  package.json
  src/js/component/models.js
Labels: flow: assigned
